MODEL:
#  DEVICE: "cpu"
  RPN_ONLY: True
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
#INPUT:
#  MIN_SIZE_TRAIN: 100
#  MAX_SIZE_TRAIN: 200
#  MIN_SIZE_TEST: 100
#  MAX_SIZE_TEST: 200
SOLVER:
  BASE_LR: 0.001
#  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
